project:
  type: website
  output-dir: docs # delete _site

website:
  title: "Quarto Tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/kellyshee/quarto-tutorial
        aria-label: GitHub
    tools-collapse: false
    # right: 
    #   - icon: github
    #     href: https://github.com/kellyshee/quarto-tutorial
    #     aria-label: GitHub
  bread-crumbs: true
  # back-to-top-navigation: true

format:
  html:
    # respect-user-color-scheme: true
    # theme: journal
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true



